server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-value: main
          uri: https://github.com/pakoMazagon/configServer5
          search-paths: config-data
  application:
    name: config-server          
              
