server:  
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:    
    hostname: localhost
ngrok:
  enabled: true
  
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
        - id: ms-mesas
          uri: lb://ms-mesas
          predicates:
            - Path=/tables/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin