server:  
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:    
    hostname: localhost
  
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: ms-mesas
          uri: lb://ms-mesas
          predicates:
            - Path=/tables/**
          filters:
            - AuthFilter
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

ngrok:
  enabled: true            