server:  
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:    
    hostname: localhost

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**