server:  
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:    
    hostname: localhost

spring:
  cloud:
    gateway:
      # default-filters:
        # - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/products/**
          filters:
            # - RemoveRequestHeader=Cookie
            - AuthFilter
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            authorization-uri: http://127.0.0.1:9090/auth/realms/usuarios_bar/protocol/openid-connect/auth 
#            userinfo-uri: http://127.0.0.1:9090/auth/realms/usuarios_bar/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#            token-uri: http://127.0.0.1:9090/auth/realms/usuarios_bar/protocol/openid-connect/token
#        registration:
#          cliente_usuario_bar:
#            provider: keycloak
#            client-id: cliente_usuario_bar
#            client-secret: f9BqlrJTTV43kPr2cBY6bWxHRorvXShj
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/cliente_usuario_bar"            