server:
  port: ${PORT:${SERVER_PORT:0}}
  #port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:    
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true


