server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      password: password
      username: root
      authentication-database: admin
      database: productos
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
  
mongock:
  change-logs-scan-package: rest.elchoco.productos.config.dbmigrations


